import { useEffect, useState } from 'react'
import { api, del, post, put } from '../api'
import { Button, Card, Empty, PageHeader, Spinner, formatDate } from '../components'
import AdminAnalyticsTab from './AdminAnalyticsTab'
import type { AdminUser, ConfluenceMapping, ConfluenceSyncStatus, Organization, Setting } from '../types'

const weekdays = [
  { value: 'MONDAY', label: '월요일' }, { value: 'TUESDAY', label: '화요일' },
  { value: 'WEDNESDAY', label: '수요일' }, { value: 'THURSDAY', label: '목요일' },
  { value: 'FRIDAY', label: '금요일' }, { value: 'SATURDAY', label: '토요일' },
  { value: 'SUNDAY', label: '일요일' },
]

type Tab = 'analytics' | 'settings' | 'confluence' | 'users' | 'organizations' | 'pptx' | 'audit'
interface TemplateInfo { source: string; originalName: string; sizeBytes: number; sha256: string; placeholders: string[]; uploadedAt?: string }

export default function AdminPage({ notify, onSettingsChanged }: { notify: (message: string, kind?: 'success' | 'error') => void; onSettingsChanged: () => Promise<void> }) {
  const [tab, setTab] = useState<Tab>('settings')
  return <><PageHeader title="관리자 관리" description="서비스 운영 설정과 계정·조직·템플릿·감사 이력을 중앙에서 관리합니다."/><div className="tabs"><TabButton value="analytics" active={tab} set={setTab}>분석</TabButton><TabButton value="settings" active={tab} set={setTab}>서비스 설정</TabButton><TabButton value="confluence" active={tab} set={setTab}>Confluence 자동화</TabButton><TabButton value="users" active={tab} set={setTab}>사용자</TabButton><TabButton value="organizations" active={tab} set={setTab}>조직</TabButton><TabButton value="pptx" active={tab} set={setTab}>PPTX 템플릿</TabButton><TabButton value="audit" active={tab} set={setTab}>감사 로그</TabButton></div>
    {tab === 'analytics' && <AdminAnalyticsTab notify={notify}/>} {tab === 'settings' && <SettingsTab notify={notify} changed={onSettingsChanged}/>} {tab === 'confluence' && <ConfluenceTab notify={notify}/>} {tab === 'users' && <UsersTab notify={notify}/>} {tab === 'organizations' && <OrganizationsTab notify={notify}/>} {tab === 'pptx' && <PPTXTab notify={notify}/>} {tab === 'audit' && <AuditTab/>}
  </>
}

function TabButton({ value, active, set, children }: { value: Tab; active: Tab; set: (tab: Tab) => void; children: string }) { return <button className={value === active ? 'active' : ''} onClick={() => set(value)}>{children}</button> }

const labels: Record<string, string> = { 'service.name': '서비스 이름', 'service.notice': '서비스 공지', 'service.timezone': '서비스 시간대', 'workflow.enabled': '팀장 검토·승인 사용', 'workflow.week_start': '주차 시작 요일', 'auth.local_enabled': '로컬 로그인 사용', 'auth.session_hours': '세션 유효시간(시간)', 'oidc.enabled': 'Keycloak OIDC 사용', 'oidc.issuer_url': 'Issuer URL', 'oidc.client_id': 'Client ID', 'oidc.client_secret': 'Client Secret', 'oidc.redirect_url': 'Redirect URL (선택)', 'oidc.scopes': 'OIDC Scopes', 'oidc.username_claim': '사용자명 Claim', 'oidc.groups_claim': '그룹 Claim', 'oidc.admin_group': '관리자 그룹', 'oidc.auto_provision': '사용자 자동 등록', 'security.api_key_max_days': 'API 키 최대 유효일', 'analytics.retention_days': '분석 데이터 보관일', 'ai.enabled': 'AI 작성·PPTX 분석 사용', 'ai.endpoint': 'Chat Completions Endpoint', 'ai.api_key': 'AI API Key', 'ai.model': 'AI 모델', 'ai.timeout_seconds': 'AI 요청 제한시간(초)', 'ai.max_input_chars': 'AI 최대 입력 글자수', 'import.max_files': '한 번에 업로드할 PPTX 수', 'import.max_file_mb': 'PPTX 파일당 최대 MB', 'import.retention_days': 'Import 원본 보관일', 'confluence.enabled': 'Confluence 자동 수집 사용', 'confluence.base_url': 'Confluence Base URL', 'confluence.auth_mode': '인증 방식', 'confluence.username': 'Service Account', 'confluence.password': 'Service Account 비밀번호', 'confluence.include_spaces': '포함 Space (쉼표 구분)', 'confluence.exclude_spaces': '제외 Space (쉼표 구분)', 'confluence.sync_interval_minutes': '자동 수집 주기(분)', 'confluence.ai_enabled': 'Confluence AI 분류·요약 사용', 'confluence.minimum_candidate_score': '자동 후보 최소 점수', 'confluence.ai_review_min_score': 'AI 검토 최소 점수', 'confluence.analyze_body': '후보 문서 본문 분석', 'confluence.lookback_days': '첫 수집 조회 기간(일)', 'confluence.batch_size': 'API 페이지 크기', 'confluence.include_blogs': 'Blog Post 포함', 'confluence.auto_map_email_localpart': '이메일 @ 앞부분 자동 매핑', 'confluence.auto_map_username': '로그인 아이디 자동 매핑', 'confluence.work_keywords': '업무성 키워드', 'confluence.personal_space_prefixes': '개인 Space 접두사', 'confluence.score_project_space': '포함 Space 점수', 'confluence.score_creator': '본인 작성 점수', 'confluence.score_modifier': '본인 최종 수정 점수', 'confluence.score_work_keyword': '업무 키워드 점수', 'confluence.score_meeting': '회의 문서 점수', 'confluence.score_notice': '공지 문서 점수', 'confluence.score_leave': '휴가 문서 점수', 'confluence.score_personal_space': '개인 Space 점수' }

function SettingsTab({ notify, changed }: { notify: (message: string, kind?: 'success' | 'error') => void; changed: () => Promise<void> }) {
  const [settings, setSettings] = useState<Setting[]>()
  const [values, setValues] = useState<Record<string, string>>({})
  const load = () => api<Setting[]>('/api/v1/admin/settings').then(data => { setSettings(data); setValues(Object.fromEntries(data.map(item => [item.key, item.value ?? '']))) })
  useEffect(() => { load() }, [])
  const save = async () => { try { await put('/api/v1/admin/settings', { settings: values }); await load(); await changed(); notify('서비스 설정을 저장했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '설정을 저장할 수 없습니다.', 'error') } }
  const testOIDC = async () => { try { await post('/api/v1/admin/settings/oidc/test'); notify('OIDC Discovery 연결에 성공했습니다.') } catch (error) { notify(error instanceof Error ? error.message : 'OIDC 연결에 실패했습니다.', 'error') } }
  const testAI = async () => { try { const result = await post<{ model: string; items: number }>('/api/v1/admin/settings/ai/test'); notify(`${result.model} AI 연결과 Structured Output 검증에 성공했습니다.`) } catch (error) { notify(error instanceof Error ? error.message : 'AI 연결에 실패했습니다.', 'error') } }
  const testConfluence = async () => { try { await post('/api/v1/admin/settings/confluence/test'); notify('Confluence 6.9.1 REST API 연결에 성공했습니다.') } catch (error) { notify(error instanceof Error ? error.message : 'Confluence 연결에 실패했습니다.', 'error') } }
  if (!settings) return <Spinner/>
  const groups = [{ title: '일반 · 워크플로', keys: ['service.name','service.notice','service.timezone','workflow.enabled','workflow.week_start'] }, { title: '인증 · Keycloak OIDC', keys: ['auth.local_enabled','auth.session_hours','oidc.enabled','oidc.issuer_url','oidc.client_id','oidc.client_secret','oidc.redirect_url','oidc.scopes','oidc.username_claim','oidc.groups_claim','oidc.admin_group','oidc.auto_provision'] }, { title: 'AI Gateway · 과거 자료 Import', keys: ['ai.enabled','ai.endpoint','ai.api_key','ai.model','ai.timeout_seconds','ai.max_input_chars','import.max_files','import.max_file_mb','import.retention_days'] }, { title: 'Confluence 6.9.1 자동화', keys: ['confluence.enabled','confluence.base_url','confluence.auth_mode','confluence.username','confluence.password','confluence.include_spaces','confluence.exclude_spaces','confluence.sync_interval_minutes','confluence.ai_enabled','confluence.minimum_candidate_score','confluence.ai_review_min_score','confluence.analyze_body','confluence.lookback_days','confluence.batch_size','confluence.include_blogs','confluence.auto_map_email_localpart','confluence.auto_map_username','confluence.work_keywords','confluence.personal_space_prefixes','confluence.score_project_space','confluence.score_creator','confluence.score_modifier','confluence.score_work_keyword','confluence.score_meeting','confluence.score_notice','confluence.score_leave','confluence.score_personal_space'] }, { title: '보안 · 분석', keys: ['security.api_key_max_days','analytics.retention_days'] }]
  const booleanKeys = ['workflow.enabled','auth.local_enabled','oidc.enabled','oidc.auto_provision','ai.enabled','confluence.enabled','confluence.ai_enabled','confluence.analyze_body','confluence.include_blogs','confluence.auto_map_email_localpart','confluence.auto_map_username']
  return <div className="settings-stack">{groups.map(group => <Card key={group.title} title={group.title}>{group.title.startsWith('AI Gateway') && <p className="setting-help">OpenAI 호환 <code>/v1/chat/completions</code> Endpoint와 Structured Output(JSON Schema)을 지원하는 모델을 지정하세요. 사내 AI Gateway는 API Key를 비워 둘 수 있습니다.</p>}{group.title.startsWith('Confluence') && <p className="setting-help">Confluence Server 6.9.1은 PAT 대신 연동 전용 Basic Auth 계정을 사용합니다. 입력한 비밀번호와 AI API Key는 암호화되어 저장되며 브라우저로 다시 전달되지 않습니다.</p>}{group.keys.map(key => { const setting = settings.find(s => s.key === key); if (!setting) return null; const isBoolean = booleanKeys.includes(key); const secretUnavailable = setting.secret && setting.configured && !setting.available; return <label className={isBoolean ? 'toggle-row' : 'setting-row'} key={key}><span><strong>{labels[key] ?? key}</strong>{setting.secret && setting.configured && <small className={secretUnavailable ? 'secret-unavailable' : ''}>{secretUnavailable ? '복호화할 수 없음 · 다시 입력 필요' : '현재 비밀값이 안전하게 설정됨'}</small>}</span>{isBoolean ? <input type="checkbox" checked={values[key] === 'true'} onChange={e => setValues({ ...values, [key]: String(e.target.checked) })}/> : key === 'workflow.week_start' ? <select value={values[key]} onChange={e => setValues({ ...values, [key]: e.target.value })}>{weekdays.map(day => <option key={day.value} value={day.value}>{day.label}</option>)}</select> : key === 'confluence.auth_mode' ? <select value={values[key]} onChange={e => setValues({ ...values, [key]: e.target.value })}><option value="BASIC">Basic Auth</option><option value="NONE">Reverse Proxy 인증</option></select> : <input type={setting.secret ? 'password' : 'text'} value={values[key]} placeholder={secretUnavailable ? '새 비밀값을 입력하세요' : setting.secret && setting.configured ? '변경할 때만 입력' : key === 'ai.endpoint' ? 'https://ai.internal/v1/chat/completions' : key === 'confluence.base_url' ? 'https://confluence.internal/confluence' : ''} onChange={e => setValues({ ...values, [key]: e.target.value })}/>}</label>})}{group.title.startsWith('AI Gateway') && <div className="inline-test"><Button variant="secondary" onClick={testAI}>AI Structured Output 연결 시험</Button></div>}{group.title.startsWith('Confluence') && <div className="inline-test"><Button variant="secondary" onClick={testConfluence}>Confluence REST 연결 시험</Button></div>}</Card>)}<div className="admin-actions"><Button variant="secondary" onClick={testOIDC}>OIDC 연결 시험</Button><Button onClick={save}>설정 저장</Button></div></div>
}

function ConfluenceTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [status, setStatus] = useState<ConfluenceSyncStatus>(); const [mappings, setMappings] = useState<ConfluenceMapping[]>(); const [values, setValues] = useState<Record<number,string>>({}); const [actives,setActives]=useState<Record<number,boolean>>({})
  const load = async () => { const [nextStatus,nextMappings] = await Promise.all([api<ConfluenceSyncStatus>('/api/v1/admin/confluence/sync/status'),api<ConfluenceMapping[]>('/api/v1/admin/confluence/users/mappings')]); setStatus(nextStatus);setMappings(nextMappings);setValues(Object.fromEntries(nextMappings.map(item=>[item.userId,item.externalUsername??item.suggestedUsername])));setActives(Object.fromEntries(nextMappings.map(item=>[item.userId,item.active??true]))) }
  useEffect(()=>{load();const timer=window.setInterval(()=>api<ConfluenceSyncStatus>('/api/v1/admin/confluence/sync/status').then(setStatus).catch(()=>undefined),10000);return()=>window.clearInterval(timer)},[])
  const sync=async()=>{try{await post('/api/v1/admin/confluence/sync');notify('Confluence 증분 동기화를 요청했습니다.');setTimeout(load,800)}catch(error){notify(error instanceof Error?error.message:'동기화를 요청할 수 없습니다.','error')}}
  const test=async()=>{try{await post('/api/v1/admin/settings/confluence/test');notify('Confluence REST 연결에 성공했습니다.')}catch(error){notify(error instanceof Error?error.message:'연결에 실패했습니다.','error')}}
  const save=async(item:ConfluenceMapping)=>{try{await put(`/api/v1/admin/confluence/users/${item.userId}/mapping`,{externalUsername:values[item.userId],active:actives[item.userId]});await load();notify(`${item.displayName} 사용자 매핑을 저장했습니다.`)}catch(error){notify(error instanceof Error?error.message:'매핑을 저장할 수 없습니다.','error')}}
  if(!status||!mappings)return <Spinner/>;return <><Card title="자동 수집 상태" action={<span className={`sync-chip ${status.status.toLowerCase()}`}>{status.status}</span>}><div className="sync-overview"><div><small>최근 성공</small><strong>{formatDate(status.lastSuccessAt)}</strong></div><div><small>조회 / 변경</small><strong>{status.pagesScanned} / {status.pagesChanged}</strong></div><div><small>새 초안</small><strong>{status.candidatesCreated}</strong></div><div><small>매핑 / 미매핑</small><strong>{status.mappedUsers} / {status.unmappedUsers}</strong></div></div>{status.errorMessage&&<div className="import-error">{status.errorMessage}</div>}<div className="admin-actions"><Button variant="secondary" onClick={test}>연결 시험</Button><Button onClick={sync} disabled={!status.enabled||status.status==='RUNNING'}>{status.status==='RUNNING'?'동기화 중…':'지금 증분 동기화'}</Button></div></Card><Card title="Weekly ↔ Confluence 사용자 매핑"><p className="muted"><b>명시 매핑 → 이메일 @ 앞부분 → 로그인 아이디</b> 순서로 자동 연결합니다. 예: <code>hkjang@koreacb.com → hkjang</code>. 자동 판정이 유일하지 않은 사용자만 직접 지정하세요.</p><div className="table-wrap"><table><thead><tr><th>Weekly 사용자</th><th>Keycloak 이메일</th><th>Confluence 아이디</th><th>활성</th><th>매핑 근거</th><th/></tr></thead><tbody>{mappings.map(item=><tr key={item.userId}><td><strong>{item.displayName}</strong><small className="cell-sub">{item.username}</small></td><td>{item.email||'-'}</td><td><input value={values[item.userId]??''} onChange={e=>setValues({...values,[item.userId]:e.target.value})}/></td><td><input type="checkbox" checked={actives[item.userId]??true} onChange={e=>setActives({...actives,[item.userId]:e.target.checked})}/></td><td>{item.mappingSource??`추천: ${item.suggestionSource}`}</td><td><Button variant="secondary" onClick={()=>save(item)}>저장</Button></td></tr>)}</tbody></table></div></Card>{status.recentErrors.length>0&&<Card title="최근 동기화 진단"><div className="table-wrap"><table><thead><tr><th>시간</th><th>단계</th><th>Page</th><th>HTTP</th><th>내용</th></tr></thead><tbody>{status.recentErrors.map(item=><tr key={item.id}><td>{formatDate(item.createdAt)}</td><td><code>{item.phase}</code></td><td>{item.pageId??'-'}</td><td>{item.statusCode??'-'}</td><td>{item.message}</td></tr>)}</tbody></table></div></Card>}</>
}

function UsersTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [users, setUsers] = useState<AdminUser[]>(); const [organizations, setOrganizations] = useState<Organization[]>([])
  const [editing, setEditing] = useState<(AdminUser & { password: string })>()
  const [form, setForm] = useState({ username: '', displayName: '', email: '', password: '', role: 'USER', organizationId: '' })
  const load = () => Promise.all([api<AdminUser[]>('/api/v1/admin/users'), api<Organization[]>('/api/v1/admin/organizations')]).then(([u,o]) => { setUsers(u); setOrganizations(o) })
  useEffect(() => { load() }, [])
  const create = async () => { try { await post('/api/v1/admin/users', { ...form, organizationId: form.organizationId ? Number(form.organizationId) : null }); setForm({ username: '', displayName: '', email: '', password: '', role: 'USER', organizationId: '' }); await load(); notify('사용자를 등록했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '등록할 수 없습니다.', 'error') } }
  const saveUser = async () => { if (!editing) return; try { await put(`/api/v1/admin/users/${editing.id}`, { displayName: editing.displayName, email: editing.email, password: editing.password, role: editing.role, organizationId: editing.organizationId ?? null, managerId: editing.managerId ?? null, active: editing.active }); setEditing(undefined); await load(); notify('사용자 정보를 저장했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '저장할 수 없습니다.', 'error') } }
  if (!users) return <Spinner/>
  return <><Card title="사용자 등록"><div className="inline-form wrap"><label>아이디<input value={form.username} onChange={e => setForm({...form,username:e.target.value})}/></label><label>표시 이름<input value={form.displayName} onChange={e => setForm({...form,displayName:e.target.value})}/></label><label>이메일<input value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></label><label>초기 비밀번호<input type="password" value={form.password} onChange={e => setForm({...form,password:e.target.value})} placeholder="12자 이상 또는 비움"/></label><label>역할<select value={form.role} onChange={e => setForm({...form,role:e.target.value})}><option value="USER">사용자</option><option value="TEAM_LEADER">팀장</option><option value="ORG_MANAGER">조직장</option><option value="ADMIN">관리자</option></select></label><label>조직<select value={form.organizationId} onChange={e => setForm({...form,organizationId:e.target.value})}><option value="">미지정</option>{organizations.map(o => <option value={o.id} key={o.id}>{o.name}</option>)}</select></label><Button onClick={create}>등록</Button></div></Card><Card title={`사용자 ${users.length}명`}><div className="table-wrap"><table><thead><tr><th>사용자</th><th>역할</th><th>조직</th><th>키 버전</th><th>최근 로그인</th><th>상태</th><th/></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.displayName}</strong><small className="cell-sub">{user.username} · {user.email}</small></td><td>{user.role}</td><td>{organizations.find(o => o.id === user.organizationId)?.name ?? '-'}</td><td>{user.keyVersion}</td><td>{formatDate(user.lastLoginAt)}</td><td><span className={`dot ${user.active ? 'on' : ''}`}/>{user.active ? '활성' : '비활성'}</td><td><button className="text-button" onClick={() => setEditing({...user,password:''})}>편집</button></td></tr>)}</tbody></table></div></Card>
    {editing && <div className="modal-backdrop" onClick={() => setEditing(undefined)}><div className="modal" onClick={e => e.stopPropagation()}><header><h2>{editing.username} 사용자 편집</h2><button onClick={() => setEditing(undefined)}>×</button></header><div className="modal-form"><label>표시 이름<input value={editing.displayName} onChange={e => setEditing({...editing,displayName:e.target.value})}/></label><label>이메일<input value={editing.email} onChange={e => setEditing({...editing,email:e.target.value})}/></label><label>역할<select value={editing.role} onChange={e => setEditing({...editing,role:e.target.value as AdminUser['role']})}><option value="USER">사용자</option><option value="TEAM_LEADER">팀장</option><option value="ORG_MANAGER">조직장</option><option value="ADMIN">관리자</option></select></label><label>조직<select value={editing.organizationId ?? ''} onChange={e => setEditing({...editing,organizationId:e.target.value?Number(e.target.value):undefined})}><option value="">미지정</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>검토 책임자<select value={editing.managerId ?? ''} onChange={e => setEditing({...editing,managerId:e.target.value?Number(e.target.value):undefined})}><option value="">미지정</option>{users.filter(u=>u.id!==editing.id&&u.role!=='USER').map(u=><option key={u.id} value={u.id}>{u.displayName}</option>)}</select></label><label>새 비밀번호<input type="password" value={editing.password} onChange={e => setEditing({...editing,password:e.target.value})} placeholder="변경할 때만 12자 이상 입력"/></label><label className="checkbox-line"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> 활성 계정</label></div><footer><Button variant="secondary" onClick={()=>setEditing(undefined)}>취소</Button><Button onClick={saveUser}>저장</Button></footer></div></div>}
  </>
}

function OrganizationsTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [items, setItems] = useState<Organization[]>(); const [name,setName]=useState('');const [code,setCode]=useState('');const [parent,setParent]=useState('')
  const load=()=>api<Organization[]>('/api/v1/admin/organizations').then(setItems);useEffect(()=>{load()},[])
  const create=async()=>{try{await post('/api/v1/admin/organizations',{name,code,parentId:parent?Number(parent):null});setName('');setCode('');setParent('');await load();notify('조직을 등록했습니다.')}catch(error){notify(error instanceof Error?error.message:'등록할 수 없습니다.','error')}}
  if(!items)return <Spinner/>;return <><Card title="조직 등록"><div className="inline-form"><label>조직명<input value={name} onChange={e=>setName(e.target.value)}/></label><label>코드<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>상위 조직<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">최상위</option>{items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><Button onClick={create}>등록</Button></div></Card><Card title="조직 구조"><div className="org-list">{items.map(org=><div key={org.id}><span className="org-icon">▦</span><div><strong>{org.name}</strong><small>{org.code} · 구성원 {org.userCount}명</small></div><span>{org.parentId?`상위: ${items.find(o=>o.id===org.parentId)?.name??'-'}`:'최상위'}</span></div>)}</div></Card></>
}

function PPTXTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [info,setInfo]=useState<TemplateInfo>();const [file,setFile]=useState<File>();const [busy,setBusy]=useState(false);const load=()=>api<TemplateInfo>('/api/v1/admin/pptx-template').then(setInfo);useEffect(()=>{load()},[])
  const upload=async()=>{if(!file)return;setBusy(true);try{const body=new FormData();body.append('file',file);await api('/api/v1/admin/pptx-template',{method:'POST',body});await load();setFile(undefined);notify('PPTX 템플릿을 적용했습니다.')}catch(error){notify(error instanceof Error?error.message:'업로드할 수 없습니다.','error')}finally{setBusy(false)}}
  const reset=async()=>{if(!confirm('사용자 템플릿을 삭제하고 기본 템플릿으로 되돌리시겠습니까?'))return;await del('/api/v1/admin/pptx-template');await load();notify('기본 PPTX 템플릿으로 초기화했습니다.')}
  if(!info)return <Spinner/>;return <><Card title="현재 내보내기 템플릿"><div className="template-info"><span className="ppt-icon">P</span><div><strong>{info.originalName}</strong><p>{info.source==='custom'?'관리자 템플릿':'Weekly 기본 템플릿'} · {(info.sizeBytes/1024).toFixed(1)} KB {info.uploadedAt&&`· ${formatDate(info.uploadedAt)}`}</p><code>SHA-256 {info.sha256.slice(0,16)}…</code></div>{info.source==='custom'&&<Button variant="danger" onClick={reset}>기본값 복원</Button>}</div><div className="placeholder-list">{info.placeholders.map(token=><code key={token}>{token}</code>)}</div></Card><Card title="동일 규격 템플릿 등록"><p className="muted">기준 PPTX의 디자인은 그대로 유지됩니다. 바뀔 텍스트 상자를 아래 토큰으로 교체한 뒤 업로드하세요. <b>{'{{THIS_WEEK}}'}</b>와 <b>{'{{NEXT_WEEK}}'}</b>는 필수입니다.</p><div className="token-guide"><div><code>{'{{WEEK_SCHEDULE}}'}</code><span>주간 일정</span></div><div><code>{'{{THIS_WEEK}}'}</code><span>이번 주 한 일 목록</span></div><div><code>{'{{NEXT_WEEK}}'}</code><span>다음 주 할 일 목록</span></div><div><code>{'{{ISSUES}}'}</code><span>이슈 목록</span></div><div><code>{'{{AUTHOR}}'} · {'{{TEAM}}'}</code><span>작성자 · 조직</span></div></div><div className="upload-row"><input type="file" accept=".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation" onChange={e=>setFile(e.target.files?.[0])}/><Button onClick={upload} disabled={!file||busy}>{busy?'검증·적용 중…':'템플릿 적용'}</Button></div></Card></>
}

function AuditTab(){const [logs,setLogs]=useState<Record<string,unknown>[]>();useEffect(()=>{api<Record<string,unknown>[]>('/api/v1/admin/audit').then(setLogs)},[]);if(!logs)return <Spinner/>;return <Card title="최근 감사 로그">{!logs.length?<Empty>감사 로그가 없습니다.</Empty>:<div className="table-wrap"><table><thead><tr><th>시간</th><th>행위자</th><th>작업</th><th>대상</th><th>IP</th></tr></thead><tbody>{logs.map((log,index)=><tr key={index}><td>{formatDate(String(log.createdAt))}</td><td>{String(log.actor)}</td><td><code>{String(log.action)}</code></td><td>{String(log.resourceType)} / {String(log.resourceId)}</td><td>{String(log.ipAddress??'-')}</td></tr>)}</tbody></table></div>}</Card>}
