import { useEffect, useState } from 'react'
import { api, del, post, put } from '../api'
import { Button, Card, Empty, PageHeader, Spinner, formatDate } from '../components'
import type { AdminUser, Organization, Setting } from '../types'

type Tab = 'settings' | 'users' | 'organizations' | 'pptx' | 'audit'
interface TemplateInfo { source: string; originalName: string; sizeBytes: number; sha256: string; placeholders: string[]; uploadedAt?: string }

export default function AdminPage({ notify, onSettingsChanged }: { notify: (message: string, kind?: 'success' | 'error') => void; onSettingsChanged: () => Promise<void> }) {
  const [tab, setTab] = useState<Tab>('settings')
  return <><PageHeader title="관리자 관리" description="서비스 운영 설정과 계정·조직·템플릿·감사 이력을 중앙에서 관리합니다."/><div className="tabs"><TabButton value="settings" active={tab} set={setTab}>서비스 설정</TabButton><TabButton value="users" active={tab} set={setTab}>사용자</TabButton><TabButton value="organizations" active={tab} set={setTab}>조직</TabButton><TabButton value="pptx" active={tab} set={setTab}>PPTX 템플릿</TabButton><TabButton value="audit" active={tab} set={setTab}>감사 로그</TabButton></div>
    {tab === 'settings' && <SettingsTab notify={notify} changed={onSettingsChanged}/>} {tab === 'users' && <UsersTab notify={notify}/>} {tab === 'organizations' && <OrganizationsTab notify={notify}/>} {tab === 'pptx' && <PPTXTab notify={notify}/>} {tab === 'audit' && <AuditTab/>}
  </>
}

function TabButton({ value, active, set, children }: { value: Tab; active: Tab; set: (tab: Tab) => void; children: string }) { return <button className={value === active ? 'active' : ''} onClick={() => set(value)}>{children}</button> }

const labels: Record<string, string> = { 'service.name': '서비스 이름', 'service.notice': '서비스 공지', 'workflow.enabled': '팀장 검토·승인 사용', 'workflow.week_start': '주차 시작 요일', 'auth.local_enabled': '로컬 로그인 사용', 'auth.session_hours': '세션 유효시간(시간)', 'oidc.enabled': 'Keycloak OIDC 사용', 'oidc.issuer_url': 'Issuer URL', 'oidc.client_id': 'Client ID', 'oidc.client_secret': 'Client Secret', 'oidc.redirect_url': 'Redirect URL (선택)', 'oidc.scopes': 'OIDC Scopes', 'oidc.username_claim': '사용자명 Claim', 'oidc.groups_claim': '그룹 Claim', 'oidc.admin_group': '관리자 그룹', 'oidc.auto_provision': '사용자 자동 등록', 'security.api_key_max_days': 'API 키 최대 유효일', 'analytics.retention_days': '분석 데이터 보관일' }

function SettingsTab({ notify, changed }: { notify: (message: string, kind?: 'success' | 'error') => void; changed: () => Promise<void> }) {
  const [settings, setSettings] = useState<Setting[]>()
  const [values, setValues] = useState<Record<string, string>>({})
  const load = () => api<Setting[]>('/api/v1/admin/settings').then(data => { setSettings(data); setValues(Object.fromEntries(data.map(item => [item.key, item.value ?? '']))) })
  useEffect(() => { load() }, [])
  const save = async () => { try { await put('/api/v1/admin/settings', { settings: values }); await load(); await changed(); notify('서비스 설정을 저장했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '설정을 저장할 수 없습니다.', 'error') } }
  const testOIDC = async () => { try { await post('/api/v1/admin/settings/oidc/test'); notify('OIDC Discovery 연결에 성공했습니다.') } catch (error) { notify(error instanceof Error ? error.message : 'OIDC 연결에 실패했습니다.', 'error') } }
  if (!settings) return <Spinner/>
  const groups = [{ title: '일반 · 워크플로', keys: ['service.name','service.notice','workflow.enabled','workflow.week_start'] }, { title: '인증 · Keycloak OIDC', keys: ['auth.local_enabled','auth.session_hours','oidc.enabled','oidc.issuer_url','oidc.client_id','oidc.client_secret','oidc.redirect_url','oidc.scopes','oidc.username_claim','oidc.groups_claim','oidc.admin_group','oidc.auto_provision'] }, { title: '보안 · 분석', keys: ['security.api_key_max_days','analytics.retention_days'] }]
  return <div className="settings-stack">{groups.map(group => <Card key={group.title} title={group.title}>{group.keys.map(key => { const setting = settings.find(s => s.key === key); if (!setting) return null; const isBoolean = ['workflow.enabled','auth.local_enabled','oidc.enabled','oidc.auto_provision'].includes(key); return <label className={isBoolean ? 'toggle-row' : 'setting-row'} key={key}><span><strong>{labels[key] ?? key}</strong>{setting.secret && setting.configured && <small>현재 비밀값이 설정됨</small>}</span>{isBoolean ? <input type="checkbox" checked={values[key] === 'true'} onChange={e => setValues({ ...values, [key]: String(e.target.checked) })}/> : key === 'workflow.week_start' ? <select value={values[key]} onChange={e => setValues({ ...values, [key]: e.target.value })}><option value="MONDAY">월요일</option><option value="SUNDAY">일요일</option></select> : <input type={setting.secret ? 'password' : 'text'} value={values[key]} placeholder={setting.secret && setting.configured ? '변경할 때만 입력' : ''} onChange={e => setValues({ ...values, [key]: e.target.value })}/>}</label>})}</Card>)}<div className="admin-actions"><Button variant="secondary" onClick={testOIDC}>OIDC 연결 시험</Button><Button onClick={save}>설정 저장</Button></div></div>
}

function UsersTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [users, setUsers] = useState<AdminUser[]>(); const [organizations, setOrganizations] = useState<Organization[]>([])
  const [editing, setEditing] = useState<(AdminUser & { password: string })>()
  const [form, setForm] = useState({ username: '', displayName: '', email: '', password: '', role: 'USER', organizationId: '' })
  const load = () => Promise.all([api<AdminUser[]>('/api/v1/admin/users'), api<Organization[]>('/api/v1/admin/organizations')]).then(([u,o]) => { setUsers(u); setOrganizations(o) })
  useEffect(() => { load() }, [])
  const create = async () => { try { await post('/api/v1/admin/users', { ...form, organizationId: form.organizationId ? Number(form.organizationId) : null }); setForm({ username: '', displayName: '', email: '', password: '', role: 'USER', organizationId: '' }); await load(); notify('사용자를 등록했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '등록할 수 없습니다.', 'error') } }
  const saveUser = async () => { if (!editing) return; try { await put(`/api/v1/admin/users/${editing.id}`, { displayName: editing.displayName, email: editing.email, password: editing.password, role: editing.role, organizationId: editing.organizationId ?? null, managerId: editing.managerId ?? null, active: editing.active }); setEditing(undefined); await load(); notify('사용자 정보를 저장했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '저장할 수 없습니다.', 'error') } }
  if (!users) return <Spinner/>
  return <><Card title="사용자 등록"><div className="inline-form wrap"><label>아이디<input value={form.username} onChange={e => setForm({...form,username:e.target.value})}/></label><label>표시 이름<input value={form.displayName} onChange={e => setForm({...form,displayName:e.target.value})}/></label><label>이메일<input value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></label><label>초기 비밀번호<input type="password" value={form.password} onChange={e => setForm({...form,password:e.target.value})} placeholder="12자 이상 또는 비움"/></label><label>역할<select value={form.role} onChange={e => setForm({...form,role:e.target.value})}><option value="USER">사용자</option><option value="TEAM_LEADER">팀장</option><option value="ORG_MANAGER">조직장</option><option value="ADMIN">관리자</option></select></label><label>조직<select value={form.organizationId} onChange={e => setForm({...form,organizationId:e.target.value})}><option value="">미지정</option>{organizations.map(o => <option value={o.id} key={o.id}>{o.name}</option>)}</select></label><Button onClick={create}>등록</Button></div></Card><Card title={`사용자 ${users.length}명`}><div className="table-wrap"><table><thead><tr><th>사용자</th><th>역할</th><th>조직</th><th>키 버전</th><th>최근 로그인</th><th>상태</th><th/></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.displayName}</strong><small className="cell-sub">{user.username} · {user.email}</small></td><td>{user.role}</td><td>{organizations.find(o => o.id === user.organizationId)?.name ?? '-'}</td><td>{user.keyVersion}</td><td>{formatDate(user.lastLoginAt)}</td><td><span className={`dot ${user.active ? 'on' : ''}`}/>{user.active ? '활성' : '비활성'}</td><td><button className="text-button" onClick={() => setEditing({...user,password:''})}>편집</button></td></tr>)}</tbody></table></div></Card>
    {editing && <div className="modal-backdrop" onClick={() => setEditing(undefined)}><div className="modal" onClick={e => e.stopPropagation()}><header><h2>{editing.username} 사용자 편집</h2><button onClick={() => setEditing(undefined)}>×</button></header><div className="modal-form"><label>표시 이름<input value={editing.displayName} onChange={e => setEditing({...editing,displayName:e.target.value})}/></label><label>이메일<input value={editing.email} onChange={e => setEditing({...editing,email:e.target.value})}/></label><label>역할<select value={editing.role} onChange={e => setEditing({...editing,role:e.target.value as AdminUser['role']})}><option value="USER">사용자</option><option value="TEAM_LEADER">팀장</option><option value="ORG_MANAGER">조직장</option><option value="ADMIN">관리자</option></select></label><label>조직<select value={editing.organizationId ?? ''} onChange={e => setEditing({...editing,organizationId:e.target.value?Number(e.target.value):undefined})}><option value="">미지정</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>검토 책임자<select value={editing.managerId ?? ''} onChange={e => setEditing({...editing,managerId:e.target.value?Number(e.target.value):undefined})}><option value="">미지정</option>{users.filter(u=>u.id!==editing.id&&u.role!=='USER').map(u=><option key={u.id} value={u.id}>{u.displayName}</option>)}</select></label><label>새 비밀번호<input type="password" value={editing.password} onChange={e => setEditing({...editing,password:e.target.value})} placeholder="변경할 때만 12자 이상 입력"/></label><label className="checkbox-line"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> 활성 계정</label></div><footer><Button variant="secondary" onClick={()=>setEditing(undefined)}>취소</Button><Button onClick={saveUser}>저장</Button></footer></div></div>}
  </>
}

function OrganizationsTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [items, setItems] = useState<Organization[]>(); const [name,setName]=useState('');const [code,setCode]=useState('');const [parent,setParent]=useState('')
  const load=()=>api<Organization[]>('/api/v1/admin/organizations').then(setItems);useEffect(()=>{load()},[])
  const create=async()=>{try{await post('/api/v1/admin/organizations',{name,code,parentId:parent?Number(parent):null});setName('');setCode('');setParent('');await load();notify('조직을 등록했습니다.')}catch(error){notify(error instanceof Error?error.message:'등록할 수 없습니다.','error')}}
  if(!items)return <Spinner/>;return <><Card title="조직 등록"><div className="inline-form"><label>조직명<input value={name} onChange={e=>setName(e.target.value)}/></label><label>코드<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>상위 조직<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">최상위</option>{items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><Button onClick={create}>등록</Button></div></Card><Card title="조직 구조"><div className="org-list">{items.map(org=><div key={org.id}><span className="org-icon">▦</span><div><strong>{org.name}</strong><small>{org.code} · 구성원 {org.userCount}명</small></div><span>{org.parentId?`상위: ${items.find(o=>o.id===org.parentId)?.name??'-'}`:'최상위'}</span></div>)}</div></Card></>
}

function PPTXTab({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [info,setInfo]=useState<TemplateInfo>();const [file,setFile]=useState<File>();const [busy,setBusy]=useState(false);const load=()=>api<TemplateInfo>('/api/v1/admin/pptx-template').then(setInfo);useEffect(()=>{load()},[])
  const upload=async()=>{if(!file)return;setBusy(true);try{const body=new FormData();body.append('file',file);await api('/api/v1/admin/pptx-template',{method:'POST',body});await load();setFile(undefined);notify('PPTX 템플릿을 적용했습니다.')}catch(error){notify(error instanceof Error?error.message:'업로드할 수 없습니다.','error')}finally{setBusy(false)}}
  const reset=async()=>{if(!confirm('사용자 템플릿을 삭제하고 기본 템플릿으로 되돌리시겠습니까?'))return;await del('/api/v1/admin/pptx-template');await load();notify('기본 PPTX 템플릿으로 초기화했습니다.')}
  if(!info)return <Spinner/>;return <><Card title="현재 내보내기 템플릿"><div className="template-info"><span className="ppt-icon">P</span><div><strong>{info.originalName}</strong><p>{info.source==='custom'?'관리자 템플릿':'Weekly 기본 템플릿'} · {(info.sizeBytes/1024).toFixed(1)} KB {info.uploadedAt&&`· ${formatDate(info.uploadedAt)}`}</p><code>SHA-256 {info.sha256.slice(0,16)}…</code></div>{info.source==='custom'&&<Button variant="danger" onClick={reset}>기본값 복원</Button>}</div><div className="placeholder-list">{info.placeholders.map(token=><code key={token}>{token}</code>)}</div></Card><Card title="동일 규격 템플릿 등록"><p className="muted">기준 PPTX의 디자인은 그대로 유지됩니다. 바뀔 텍스트 상자를 아래 토큰으로 교체한 뒤 업로드하세요. <b>{'{{THIS_WEEK}}'}</b>와 <b>{'{{NEXT_WEEK}}'}</b>는 필수입니다.</p><div className="token-guide"><div><code>{'{{WEEK_SCHEDULE}}'}</code><span>주간 일정</span></div><div><code>{'{{THIS_WEEK}}'}</code><span>이번 주 한 일 목록</span></div><div><code>{'{{NEXT_WEEK}}'}</code><span>다음 주 할 일 목록</span></div><div><code>{'{{ISSUES}}'}</code><span>이슈 목록</span></div><div><code>{'{{AUTHOR}}'} · {'{{TEAM}}'}</code><span>작성자 · 조직</span></div></div><div className="upload-row"><input type="file" accept=".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation" onChange={e=>setFile(e.target.files?.[0])}/><Button onClick={upload} disabled={!file||busy}>{busy?'검증·적용 중…':'템플릿 적용'}</Button></div></Card></>
}

function AuditTab(){const [logs,setLogs]=useState<Record<string,unknown>[]>();useEffect(()=>{api<Record<string,unknown>[]>('/api/v1/admin/audit').then(setLogs)},[]);if(!logs)return <Spinner/>;return <Card title="최근 감사 로그">{!logs.length?<Empty>감사 로그가 없습니다.</Empty>:<div className="table-wrap"><table><thead><tr><th>시간</th><th>행위자</th><th>작업</th><th>대상</th><th>IP</th></tr></thead><tbody>{logs.map((log,index)=><tr key={index}><td>{formatDate(String(log.createdAt))}</td><td>{String(log.actor)}</td><td><code>{String(log.action)}</code></td><td>{String(log.resourceType)} / {String(log.resourceId)}</td><td>{String(log.ipAddress??'-')}</td></tr>)}</tbody></table></div>}</Card>}
