import { useEffect, useState } from 'react'
import { api, del, put } from '../api'
import { Button, Card, Empty, PageHeader, SourceBadge, Spinner, StatusBadge, formatDate } from '../components'
import type { Report, ReportItem, ReportListItem } from '../types'

const blankItem = (): ReportItem => ({ category: '', title: '', currentResult: '', nextPlan: '', issue: '', progress: 0, sortOrder: 0 })

export default function ReportsPage({ notify }: { notify: (message: string, kind?: 'success' | 'error') => void }) {
  const [reports, setReports] = useState<ReportListItem[]>()
  const [selected, setSelected] = useState<Report>()
  const [status, setStatus] = useState('')
  const [editing, setEditing] = useState(false)
  const [summary, setSummary] = useState('')
  const [items, setItems] = useState<ReportItem[]>([])
  const [busy, setBusy] = useState(false)
  const load = () => api<ReportListItem[]>(`/api/v1/reports${status ? `?status=${status}` : ''}`).then(setReports).catch(error => notify(error.message, 'error'))
  useEffect(() => { void load() }, [status])
  const open = async (id: number) => { try { const report = await api<Report>(`/api/v1/reports/${id}`); setSelected(report); setSummary(report.summary); setItems(report.items.map(item => ({ ...item }))); setEditing(false) } catch (error) { notify(error instanceof Error ? error.message : '보고서를 열 수 없습니다.', 'error') } }
  const close = () => { setSelected(undefined); setEditing(false) }
  const updateItem = (index: number, values: Partial<ReportItem>) => setItems(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...values } : item))
  const save = async () => { if (!selected) return; const prepared = items.filter(item => item.title.trim()); if (!prepared.length) { notify('업무 항목을 하나 이상 입력하세요.', 'error'); return } setBusy(true); try { await put(`/api/v1/reports/${selected.id}`, { version: selected.version, summary, sourceType: selected.sourceType, items: prepared.map((item, index) => ({ ...item, sortOrder: index })) }); await Promise.all([load(), open(selected.id)]); setEditing(false); notify('주간보고 수정사항을 저장했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '보고서를 수정할 수 없습니다.', 'error') } finally { setBusy(false) } }
  const remove = async () => { if (!selected || !confirm(`${selected.weekStart} 주간보고를 삭제하시겠습니까? 삭제한 보고서는 복구할 수 없습니다.`)) return; setBusy(true); try { await del(`/api/v1/reports/${selected.id}?version=${selected.version}`); close(); await load(); notify('주간보고를 삭제했습니다.') } catch (error) { notify(error instanceof Error ? error.message : '보고서를 삭제할 수 없습니다.', 'error') } finally { setBusy(false) } }

  return <><PageHeader title="과거 보고" description="이전 주간보고를 조회하고 직접 수정·삭제하거나 PPTX로 내보냅니다." action={<select value={status} onChange={e => setStatus(e.target.value)}><option value="">전체 상태</option><option value="DRAFT">작성 중</option><option value="SUBMITTED">검토 대기</option><option value="REVISION_REQUESTED">반려</option><option value="APPROVED">승인</option><option value="CLOSED">확정</option></select>} />
    {!reports ? <Spinner/> : !reports.length ? <Empty>조회할 보고서가 없습니다.</Empty> : <Card><div className="table-wrap"><table><thead><tr><th>주차</th><th>작성자</th><th>요약</th><th>출처</th><th>상태</th><th>수정일</th><th/></tr></thead><tbody>{reports.map(report => <tr key={report.id} onClick={() => open(report.id)}><td>{report.weekStart}</td><td>{report.displayName}</td><td className="truncate">{report.summary || '-'}</td><td><SourceBadge source={report.sourceType}/></td><td><StatusBadge status={report.status}/></td><td>{formatDate(report.updatedAt)}</td><td><a className="icon-button" href={`/api/v1/reports/${report.id}/export.pptx`} onClick={e => e.stopPropagation()} title="PPTX 다운로드">↓</a></td></tr>)}</tbody></table></div></Card>}
    {selected && <div className="modal-backdrop" onClick={close}><div className="modal wide" onClick={e => e.stopPropagation()}><header><div><StatusBadge status={selected.status}/> <SourceBadge source={selected.sourceType}/><h2>{selected.displayName} · {selected.weekStart}</h2></div><button onClick={close}>×</button></header>{editing ? <div className="history-editor"><label>주간 요약<textarea value={summary} onChange={e => setSummary(e.target.value)} maxLength={10000}/></label>{(selected.status === 'SUBMITTED' || selected.status === 'APPROVED') && <div className="edit-notice">저장하면 기존 검토 결과가 해제되고 작성 중 상태로 돌아갑니다.</div>}{items.map((item, index) => <section key={item.id ?? index}><header><strong>업무 {index + 1}</strong>{items.length > 1 && <button className="remove-button" onClick={() => setItems(current => current.filter((_, itemIndex) => itemIndex !== index))}>항목 삭제</button>}</header><div className="form-grid title-grid"><label>구분<input value={item.category} onChange={e => updateItem(index, { category: e.target.value })}/></label><label>업무 제목<input value={item.title} onChange={e => updateItem(index, { title: e.target.value })}/></label><label>진척도 <b>{item.progress}%</b><input type="range" min="0" max="100" step="5" value={item.progress} onChange={e => updateItem(index, { progress: Number(e.target.value) })}/></label></div><div className="form-grid content-grid"><label>금주 실적<textarea value={item.currentResult} onChange={e => updateItem(index, { currentResult: e.target.value })}/></label><label>차주 계획<textarea value={item.nextPlan} onChange={e => updateItem(index, { nextPlan: e.target.value })}/></label><label>이슈<textarea value={item.issue} onChange={e => updateItem(index, { issue: e.target.value })}/></label></div></section>)}<Button variant="secondary" onClick={() => setItems(current => [...current, blankItem()])}>+ 업무 항목 추가</Button></div> : <><p>{selected.summary}</p><div className="detail-items">{selected.items.map(item => <section key={item.id}><h3>{item.title} <small>{item.progress}%</small></h3><div><b>금주 실적</b><p>{item.currentResult || '-'}</p><b>차주 계획</b><p>{item.nextPlan || '-'}</p><b>이슈</b><p>{item.issue || '-'}</p></div></section>)}</div></>}<footer>{editing ? <><Button variant="secondary" onClick={() => { setEditing(false); setSummary(selected.summary); setItems(selected.items.map(item => ({ ...item }))) }} disabled={busy}>취소</Button><Button onClick={save} disabled={busy}>{busy ? '저장 중…' : '수정 저장'}</Button></> : <><Button variant="danger" onClick={remove} disabled={busy}>삭제</Button><Button variant="secondary" onClick={() => setEditing(true)}>수정</Button><a className="button primary" href={`/api/v1/reports/${selected.id}/export.pptx`}>PPTX 다운로드</a></>}</footer></div></div>}
  </>
}
